# CodeRabbit Configuration Template
# Complete reference: https://docs.coderabbit.ai/reference/configuration

language: "en-US"
tone_instructions: ""
early_access: false
enable_free_tier: true

reviews:
  profile: "assertive"  # More strict for automotive/embedded standards
  request_changes_workflow: true  # Require changes for violations
  high_level_summary: true
  high_level_summary_placeholder: "@coderabbitai summary"
  high_level_summary_in_walkthrough: false
  auto_title_placeholder: "@coderabbitai"
  auto_title_instructions: ""
  review_status: true
  commit_status: true
  fail_commit_status: true  # Fail on standards violations
  collapse_walkthrough: false
  changed_files_summary: true
  sequence_diagrams: true
  estimate_code_review_effort: true
  assess_linked_issues: true
  related_issues: true
  related_prs: true
  suggested_labels: true
  auto_apply_labels: false
  suggested_reviewers: true
  auto_assign_reviewers: false
  poem: false  # Disable poem for professional context
  
  labeling_instructions:
    - "automotive"
    - "embedded"
    - "safety-critical"
    - "cpp14"
    - "autosar"
    - "misra"
    - "google-style"
  
  path_filters:
    - "src/**"
    - "include/**"
    - "!test/**"
    - "!vendor/**"
    - "!third_party/**"
  
  path_instructions:
    - path: "**/*.cpp"
      instructions: "Apply C++14 guidelines, AUTOSAR C++14, and MISRA C++ rules strictly. Check for memory safety, no dynamic memory allocation, no exceptions, no RTTI."
    - path: "**/*.h"
      instructions: "Apply Google C++ Style Guide for headers. Ensure include guards, minimal includes, and proper namespace usage."
    - path: "**/*.c"
      instructions: "Apply MISRA C:2012 guidelines. Check for no recursion, no dynamic memory, defensive programming."
    - path: "**/autosar/**"
      instructions: "Strict AUTOSAR compliance required. No deviations allowed."
    - path: "**/safety/**"
      instructions: "ASIL compliance required. No runtime errors, defensive coding, full coverage required."
  
  abort_on_close: true
  disable_cache: false
  
  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords: ["WIP", "DRAFT", "TODO"]
    labels: ["!wip", "!draft"]
    drafts: false
    base_branches: ["develop", "feature/*", "hotfix/*"]
  
  finishing_touches:
    docstrings:
      enabled: true
    unit_tests:
      enabled: true
  
  pre_merge_checks:
    docstrings:
      mode: "error"  # Error for missing docstrings in safety-critical code
      threshold: 95  # High threshold for automotive
    title:
      mode: "warning"
      requirements: "Title must follow conventional commits pattern: feat|fix|docs|style|refactor|test|chore(scope): description"
    description:
      mode: "warning"
    issue_assessment:
      mode: "error"  # Must address linked safety issues
  
  tools:
    ast-grep:
      rule_dirs: [".coderabbit/rules"]
      util_dirs: [".coderabbit/utils"]
      essential_rules: true
      packages: ["cpp", "google-style", "safety"]
    
    cppcheck:
      enabled: true
    
    clippy:
      enabled: true
    
    gitleaks:
      enabled: true
    
    semgrep:
      enabled: true
      config_file: ".semgrep.yml"
    
    # Additional automotive-specific tools
    misra-checker:
      enabled: true
    
    autosar-checker:
      enabled: true

chat:
  art: false  # Professional tone for automotive
  auto_reply: true
  integrations:
    jira:
      usage: "auto"
    linear:
      usage: "auto"

knowledge_base:
  opt_out: false
  web_search:
    enabled: true
  
  code_guidelines:
    enabled: true
    filePatterns:
      - "**/CODING_STANDARDS.md"
      - "**/AUTOSAR_*.md"
      - "**/MISRA_*.md"
      - "**/GOOGLE_STYLE.md"
      - "**/safety_requirements.md"
      - "**/design_rules.md"
  
  learnings:
    scope: "global"
  
  issues:
    scope: "global"
  
  jira:
    usage: "auto"
    project_keys: ["AUTO", "SAFETY", "EMBED"]
  
  linear:
    usage: "auto"
    team_keys: ["ENG", "AUTOSAR", "SAFETY"]
  
  pull_requests:
    scope: "global"
  
  mcp:
    usage: "auto"
    disabled_servers: []

code_generation:
  docstrings:
    language: "en-US"
    path_instructions:
      - path: "**/*.cpp"
        instructions: "Use Doxygen-style comments with @brief, @param, @return, @throws. Include safety considerations."
      - path: "**/*.h"
        instructions: "Detailed class and function documentation. Include thread safety, memory ownership, and exception guarantees."
      - path: "**/autosar/**"
        instructions: "AUTOSAR-compliant documentation with requirement tracing tags."
  
  unit_tests:
    path_instructions:
      - path: "**/*.cpp"
        instructions: "Google Test framework. 100% MC/DC coverage for safety-critical code. Include boundary value analysis."
      - path: "**/safety/**"
        instructions: "ASIL-D compliance tests. Fault injection, robustness testing, and timing analysis required."
